### ISSUE TITLE
ClassNotFoundException on adding and running new java file

### ISSUE THREAD

**Issue by manastalukdar** [microsoft/vscode-java-debug#606]
On adding a new Java file into an existing project and clicking on the `Run` or `Debug` text at the top of `main` function results in ClassNotFoundException. Same issue also happens when manually adding the mainClass entry in the launch.json file.

**Workaround:** Do a _Full_ `Java: Force Java Compilation` from the command palette before attempting to `Run` or `Debug` the `main` function. Or, restart/reload VSCode, which appears to trigger a force compilation.

Repro repo: [here](https://github.com/manastalukdar/learning-computer-science)

**Runtime information**

JDK: 12

Debugger for Java: 0.20.0

VSCode:

```
Version: 1.37.0-insider (user setup)
Commit: 46cc0a1670b7047e610aaef1bf84f1190802e9ec
Date: 2019-07-11T05:39:42.001Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by testforstephen** [comment]
Could you share your user setting `java.debug.settings.forceBuildBeforeLaunch`? Setting it to `true` will force building the workspace before launching java program.

**Comment by manastalukdar** [comment]
It is enabled for both user and workspace.

**Comment by testforstephen** [comment]
No clue about the cause. I would suggest you to try VS Code command `Java: Clean the Java language server workspace`.

**Comment by manastalukdar** [comment]
Any update? Anything else I could try?

**Comment by testforstephen** [comment]
The repo [here](https://github.com/manastalukdar/learning-computer-science) you provided is just some empty folders, not sure how to reproduce this issue. 
Could you provide a sample project and detailed steps to reproduce this issue?

**Comment by manastalukdar** [comment]
1. Go to /learning-computer-science/tree/master/src/Miscellaneous/src/Problems/Programming in local computer.
2. Copy folder `MapWordsListToGrid` into the same parent `Programming` folder as `MapWordsListToGrid2`
3. Go inside `MapWordsListToGrid2\Java` and update the package name in the java files to be consistent with the path.
4. Now click on the Run under `MapWordsListToGrid2\Java\Solution.java`.

**Comment by testforstephen** [comment]
What is your workspace root when you open the folder in VS Code?
`learning-computer-science` or `/learning-computer-science/tree/master/src/Miscellaneous/src/Problems/Programmin`?

**Comment by manastalukdar** [comment]
![image](https://user-images.githubusercontent.com/2075466/66620475-72c9e800-eb95-11e9-82bd-ce2c8d634319.png)

**Comment by testforstephen** [comment]
![bug](https://user-images.githubusercontent.com/14052197/66620876-b152b780-ec14-11e9-9407-271a00c0e5b3.gif)

See the screenshot, i tried in my machine, it works.

**Comment by manastalukdar** [comment]
I am going to generate a gif that exhibits the problem. Will post in a few hours.

**Comment by manastalukdar** [comment]
@testforstephen I have a gif [here](https://github.com/manastalukdar/learning-computer-science/issues/68#issuecomment-541172919) that exhibits the problem.

**Comment by testforstephen** [comment]
I see, thanks.

Revisit your previous logfile from https://github.com/microsoft/vscode-java-debug/issues/606#issuecomment-540698617, i found there are some error details. Looks like the builder got some problems when generating .class file into `bin` directory.
```
!MESSAGE Error occured while building workspace. Details: 
 message: A class file was not written. The project may be inconsistent, if so try refreshing this project and building it; code: 0; resource: C:/data/devgithub/_my-projects/learning-computer-science/src/EducativeIo/Courses/GrokkingTheCodingInterview/Ch12_ModifiedBinarySearch/P2_CeilingOfANumber/Java/Solution.java;
 message: Solution cannot be resolved to a type; code: 16777218; resource: C:/data/devgithub/_my-projects/learning-computer-science/src/EducativeIo/Courses/GrokkingTheCodingInterview/Ch12_ModifiedBinarySearch/P2_CeilingOfANumber/Java/SolutionTest.java; line: 12
 message: Solution cannot be resolved to a type; code: 16777218; resource: C:/data/devgithub/_my-projects/learning-computer-science/src/EducativeIo/Courses/GrokkingTheCodingInterview/Ch12_ModifiedBinarySearch/P2_CeilingOfANumber/Java/SolutionTest.java; line: 16
 message: Solution cannot be resolved to a type; code: 16777218; resource: C:/data/devgithub/_my-projects/learning-computer-science/src/EducativeIo/Courses/GrokkingTheCodingInterview/Ch12_ModifiedBinarySearch/P2_CeilingOfANumber/Java/SolutionTest.java; line: 16
 message: Solution cannot be resolved to a type; code: 16777218; resource: C:/data/devgithub/_my-projects/learning-computer-science/src/EducativeIo/Courses/GrokkingTheCodingInterview/Ch12_ModifiedBinarySearch/P2_CeilingOfANumber/Java/SolutionTest.java; line: 21
 message: Solution cannot be resolved; code: 570425394; resource: C:/data/devgithub/_my-projects/learning-computer-science/src/EducativeIo/Courses/GrokkingTheCodingInterview/Ch12_ModifiedBinarySearch/P2_CeilingOfANumber/Java/SolutionTest.java; line: 28
 message: A class file was not written. The project may be inconsistent, if so try refreshing this project and building it; code: 0; resource: C:/data/devgithub/_my-projects/learning-computer-science/src/EducativeIo/Courses/GrokkingTheCodingInterview/Ch12_ModifiedBinarySearch/P2_CeilingOfANumber/Java/SolutionTest.java;
```

The error `A class file was not written. The project may be inconsistent, if so try refreshing this project and building it` seems a known issue for eclipse. Have googled it, and there are lots of cases for this issue, not sure which one is the root cause for your environment.

https://stackoverflow.com/questions/17154360/eclipse-build-error-a-class-file-was-not-written-the-project-may-be-inconsiste

**Comment by testforstephen** [comment]
@manasivelhankar i can reproduce it in other project, this issue is duplicated with https://github.com/eclipse/eclipse.jdt.ls/issues/1137. The root cause is the Java language server doesn't refresh the new package to underlying jdt. We're fixing it in eclipse.jdt.ls side. Current workaround is reload VS Code window.

**Comment by testforstephen** [comment]
**Language Support for Java(TM) by Red Hat** 0.51.0 released has fixed this issue.
@manastalukdar Could you try again?

**Comment by manastalukdar** [comment]
Fixed. Thanks.

**Comment by Ashvith** [comment]
So looks like I had this issue again, but I was able to resolve it.
Basically, the folder name should not contain a colon (:). I am not saying that it is just limited to colons, could be that some other symbols in the folder name could cause this issue as well. Hope that this helps others.

**Comment by hnguyenboy2001** [comment]
try deleting the .vscode folder and run it again

**Comment by mohamed-bdr** [comment]
welcome ,sir, this error appears to me when I run code
Error: Could not find or load main class Main
Caused by: java.lang.NoClassDefFoundError: videos/ClassAndObjects/Main (wrong name: Main)

**Comment by Lexiphan** [comment]
I vote here too, the problem still persists on my VS Code with the analogous message as in previous post.

**Comment by MariHGU** [comment]
This issue happens to me too. It's like viscose doent recognize when I create a file. No package is given, if I use source action to create functions, it creates a new file with only functions, no class, no package etc.

**Comment by abhishek01-github** [comment]
https://github.com/microsoft/vscode-java-debug/issues/692#issuecomment-544364859
Go for this solution, it works!!
